### PR TITLE
Added 'to satisfy' assertion

### PR DESCRIPTION
**Pull request by gertsonderby**
Per advice from @papandreou I have added this assertion.

### CODE REVIEW

**Comment by gertsonderby** [comment]
Solves #1.

**Comment by gertsonderby** [comment]
I have another set of changes adding type support for Map and List, plus a couple of assertions. Let me know if I should roll them into this PR or open another later. (They depend some on this one.)

**Comment by erikmueller** [comment]
Thanks for the PR. I'd appreciate having the other ones in separate PRs. But depending on how much they're depending on this one you can also use this PR

**Comment by erikmueller** [comment]
@gertsonderby can you elaborate on why you switched `object` for `any`? and could you maybe provide a test? Then I'm glad to merge this (and any other addition you have ;)

**Comment by gertsonderby** [comment]
`<any>` means that it can then satisfy against, well, any pattern, not just objects. Otherwise, you would rather confusingly get errors when e.g. satisfying an Immutable.List against an array, for example. As well, the assertion also allows matching against a function as in `{ foo: expect.it('to be a number') }`.

**Comment by erikmueller** [comment]
ah 💡  right, especially the last example makes sense 👍  Wanna add a test tho ;)?

**Comment by erikmueller** [comment]
@gertsonderby I was just trying out your PR when I realized that the `unexpected-react` plugin throws some weird errors.

considering this small example:
```jsx

it.only('tests', function () {
  const Foo = function ({data}) {
    return <div data={data} />
  };
  const renderer = TestUtils.createRenderer();
  const data = Immutable.fromJS({foo: 'bar'});

  renderer.render(<Foo data={data}/>);

  expect(renderer, 'to have rendered', <div data={data}/>);
});
```
the `to have rendered` assertion yields

```diff
+expected         <div data={Map { foo: 'bar' }} />
-to have rendered <div data={Map { foo: 'bar' }} />

<div data={Map { foo: 'bar' }} 
+// expected Map { foo: 'bar' } 
-// to satisfy Map { foo: 'bar' }
/>
```


I'm currently checking the implementation of @bruderstein (maybe he knows why) if I'm doing sth wrong in the react tests or if we missed sth here. Maybe there's a problem with type identification.

**Comment by bruderstein** [comment]
I think this is down to this implementation. So it's actually checking an `Immutable` against an `Immutable`, but the `to satisfy` assertion is only calling `.toJS()` on the left hand side, which means `expect(someImmutable, 'to satisfy', someImmutable)` will always fail. 

I think simply adding a `<Immutable> to [exhaustively] satisfy <Immutable>` assertion should be enough.

(for reference, the `to have rendered` assertion uses `to satisfy` on all props - `to have exactly rendered` uses `to equal`).

It might be nice to add `to equal` assertions in a similar fashion here :)

**Comment by erikmueller** [comment]
Thanks for clarifying @bruderstein Thought we find the issue much faster when pinging you ;)
So if I got this right every assertions boils down to defining it on `<Immutables>` but using their `.toJS()` counterparts for checking right?

**Comment by gertsonderby** [comment]
The `<Immutable> to satisfy <Immutable>` assertion is also one I ended up coming up with, as described by @bruderstein.

**Comment by erikmueller** [comment]
Ok, but without that I cannot merge this PR since it breaks `unexpected-react`

**Comment by gertsonderby** [comment]
It might make more sense for me to make a different PR, containing the code I've built up over a while of testing with Immutable. It's rather a lot more, but it also covers more cases. I'll need to find time to write a test suite for it, though - which I don't have right now. I'll get back to you soonest though. Hopefully next week? Otherwise in the start of the New Year.

**Comment by gertsonderby** [comment]
If you look at my [fork](https://github.com/gertsonderby/unexpected-immutable/tree/map-list), I've copied over the code, and made the existing tests run. I'll see when I can add tests to cover the new cases. Hopefully soon.

I'll close this PR for now, open a new one when I'm ready.

**Comment by erikmueller** [comment]
sounds awesome, thanks for contributing 👍

**Pull request closed without merging**
