### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by erikmueller**
@gertsonderby I had this in the pipeline but wanted to wait for your changes to be merged. What do you think?

### CODE REVIEW

**Comment by gertsonderby** [comment]
On the first glance, it looks reasonable. Am I seeing checked-in build artifacts, though? I'll take a closer look at it.

**Comment by erikmueller** [comment]
yeah, already got rid of the artifact...

**Review by gertsonderby — APPROVED** [review]
This all looks good to me.

**Comment by gertsonderby** [comment]
LGTM.

**Pull request merged**
